name: wg-blimp-testing
channels:
  - conda-forge
  - bioconda
dependencies:
  - bedtools
  - bwa
  - bwameth 0.2.0
  - click
  - fastqc
  - git
  - h5py
  - methyldackel
  - metilene
  - mosdepth
  - multiqc
  - picard
  - pysam
  - qualimap
  - r-base
  - ruamel.yaml
  - samtools
  - snakemake-minimal >=5.8
